name: ci

on:
  push:
    branches: master

jobs:
  transform:
    runs-on: ubuntu-latest
    container: flungo/inkscape
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run in container
        run: |
          /usr/bin/inkscape -f "~/icons.ai" -l "~/icons.svg"