name: ci

on:
  push:
    branches: master

jobs:
  transform:
    runs-on: ubuntu-latest
    container: flungo/inkscape
    steps:
      - name: Run in container
        run: |
          ls -lR
          ls -lR ~/
          ls -lR /
          /usr/bin/inkscape -f "~/icons.ai" -l "~/icons.svg"