name: ci

on:
  push:
    branches: master

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install - Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install - .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - name: Install - SVGO
        run: npm install -g svgo
      - name: Set CWD
        run: echo "::set-output name=CWD::${PWD}"      
        id: set-cwd
      - name: Converting to SVG
        uses: addnab/docker-run-action@v2
        with:
          image: flungo/inkscape
          options: --mount type=bind,source=${{ steps.set-cwd.outputs.CWD }},target=/mnt
          run: |
            for FILE in /mnt/Icons/*.ai; do /usr/bin/inkscape -f "${FILE}" -l "${FILE%.ai}.svg"; done
            chmod 777 /mnt/Icons/*.svg 
      - name: Minify SVG
        run: svgo -f ./Icons
        
      - name: Create project
        run: |
          dotnet new classlib -n Silvester.Pathfinder.Official.Icons -o ./project
          rm ./project/Class1.cs  

      - name: Create icon partial classes
        run: |
          cd /mnt/project
          for FILE in ./Icons/*.svg; do ./Templates/icon.bat "${FILE}"; done 
      