name: ci

on:
  push:
    tags:
      - '*.*.*'

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Setup
      - name: Install - INKSCAPE 
        run: sudo apt-get install inkscape
      - name: Install - NODE
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install - DOTNET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - name: Install - SVGO
        run: npm install -g svgo
      - name: Install - NUGET
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'
        
      # Variables  
      - name: Set - CWD
        run: echo "::set-output name=CWD::${PWD}"      
        id: set-cwd
        
      - name: Set - Tag
        id: set-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      # Conversion
      - name: SVG - Convert
        run: |
          for FILE in ./Icons/*.ai; do /usr/bin/inkscape "${FILE}" -l "${FILE%.ai}".svg;done
      - name: SVG - Minify
        run: svgo -f ./Icons --config ./Templates/svgo.config.js
        
      # Project Creation  
      - name: DOTNET - Project
        run: |
          mkdir project
          cd ./project
          sudo chmod +rx ../Templates/project.bat
          ../Templates/project.bat ${{ steps.set-tag.outputs.tag }}

      - name: DOTNET - Classes
        run: |
          sudo chmod +rx ./Templates/icon.bat
          cd ./project
          for FILE in ../Icons/*.svg; do ../Templates/icon.bat "${FILE}"; done 
          
      - name: NUGET - Package
        run: |
          ls ./project -l
          dotnet pack ./project/Silvester.Pathfinder.Reference.Icons.csproj -c Release -o ../build 
          
      - name: NUGET - Source
        run: nuget sources Add -Name Artifactory -Source https://silvester.jfrog.io/artifactory/api/nuget/silvester-nuget/silvester-pathfinder/Silvester.Pathfinder.Reference.Icons -username ${{ secrets.ARTIFACTORY_USERNAME }} -password ${{ secrets.ARTIFACTORY_PASSWORD }}
        
      - name: NUGET - Push
        if: ${{ steps.set-tag.outputs.tag != 'master'}}
        run: nuget push ../build/Silvester.Pathfinder.Reference.Icons.${{ steps.set-tag.outputs.tag }}.nupkg -Source Artifactory
          
      