name: ci

on:
  push:
    branches: master

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run in container
        run: docker run -i --mount type=bind,source="${pwd}",target="/mnt" flungo/inkscape /usr/bin/inkscape -f "/mnt/icons.ai" -l "/mnt/icons.svg"
          
      - name: Install SVGO
        run: |
          npm init -y
          npm install svgo
      - name: Minify SVG
        run: svgo -f .
        
      